### ISSUE TITLE
String generated from input ignored

### ISSUE THREAD

**Issue by averyocean65** [rldald989/String-Cheese-Lang#1]
While writing my strc program, I have an issue where a string that I generated with the help of the `readl` command.

My code is pretty much the same as [main.strc](https://github.com/rldald989/String-Cheese-Lang/blob/main/main.strc)

**Comment by rldald989** [comment]
Did you make sure to initialize the string?

**Comment by averyocean65** [comment]
The code for my string is the same as in [main.strc](https://github.com/rldald989/String-Cheese-Lang/blob/main/main.strc), so if that code isn't faulty, yes I did.

**Comment by rldald989** [comment]
I just looked into it, it isn't a problem with `readl`, you have to create a newline in your `.strc` file because of how the interpreter reads the code, otherwise, the line will be ignored, think of it like a semicolon but for a whole program(hope this helps).

**Comment by averyocean65** [comment]
So, the interpreter is using '\n' as a symbol to know a statement has ended? If so, wouldn't it make sense to also check if an EOF (End-Of-File) or null-terminating character is present too? (such as \0) Doing so could prevent small program-breaking issues like this from happening

**Comment by rldald989** [comment]
I can do this, but I think this bug could have happened because of the os you were using or the compiler, but I will fix this to make sure there are no problems in the future.
